In [1]:
import pandas as pd
import numpy as np
from IPython.display import HTML
name_stocks = ['AAPL','ABB','ABBV','TOT','WMT','DUK','CHL','HSBC']

list_error= []

for name in name_stocks: 
    df = pd.read_csv(name+'_error.csv')
    list_error.append(np.asarray(df.mean(axis=0)))

list_error

[array([2.41364248, 6.35633097]),
 array([2.57094527, 2.39609477]),
 array([2.78410393, 2.68631733]),
 array([2.43692562, 1.96877178]),
 array([2.31751655, 2.28402571]),
 array([2.45610339, 2.47724599]),
 array([2.43017083, 1.87460255]),
 array([2.80223815, 3.03568697])]

In [2]:
df_result = pd.DataFrame(list_error,columns =['Error train (%)','Error test (%)'],)
HTML(df_result.to_html(index=False))